name: vocachat
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.9+10

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & UX
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.6
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  showcaseview: ^4.0.1
  flip_card: ^0.7.0
  confetti: ^0.8.0
  emoji_picker_flutter: ^2.2.0
  circle_flags: ^2.0.1
  lottie: ^3.3.1
  google_fonts: ^6.2.1

  # Firebase Services
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.0
  firebase_messaging: ^14.9.4
  firebase_app_check: ^0.2.2+7
  cloud_functions: ^4.7.5

  # Google Services & AI
  google_sign_in: ^6.2.1
  google_mlkit_translation: ^0.13.0
  google_mlkit_language_id: ^0.13.0
  google_generative_ai: ^0.4.0

  # Device & Media
  audioplayers: ^6.0.0
  flutter_tts: ^4.2.3
  url_launcher: ^6.2.6
  image_picker: ^1.1.2
  speech_to_text: ^7.3.0

  # State & Storage
  shared_preferences: ^2.2.3
  in_app_purchase: ^3.2.0
  purchases_flutter: ^9.6.0

  # Utilities
  intl: ^0.20.2
  http: ^1.2.1
  characters: ^1.3.0
  change_app_package_name: ^1.5.0


# Mobil hedefte sürüm uyuşmazlığını çözmek için web paketini override ediyoruz
dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0 # Splash ekranı için bu paket dev_dependencies'e taşındı.

# --- Proje Yapılandırmaları ---

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/practice/
    - assets/appicon.png
    - assets/animations/success.json
    - assets/animations/Data Analysis.json
    - assets/animations/diamonds.json
    - assets/animations/diamond_icon.json
    - assets/animations/no ads icon.json
    - assets/animations/Robot says hello.json
    - assets/animations/Happy SUN.json
    - assets/animations/Support.json
    - assets/animations/Translate.json
    - assets/animations/Flags.json
    - assets/animations/olympicsports.json
    - assets/animations/chat.json # Sohbet animasyonu açıkça eklendi
    - assets/animations/The winner receives gold medal.json
    - assets/animations/Trophy.json

flutter_intl:
  enabled: false

# İkon oluşturucu ayarları
flutter_launcher_icons:
  android: true
  ios: true

  # Eski Android sürümleri için logonun ve arka planın birleşik olduğu dosya
  image_path: "assets/appicon.png"

  # Modern Android için adaptif ikon ayarları
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/appicon.png" # Arka planı ŞEFFAF olan SADECE logo

# Açılış ekranı (splash screen) ayarları
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/appicon.png
  android: true
  ios: true